var Highlight = require('./highlight');
var hljs = new Highlight();
hljs.registerLanguage('apache', require('./languages/apache.js'));
hljs.registerLanguage('bash', require('./languages/bash.js'));
hljs.registerLanguage('coffeescript', require('./languages/coffeescript.js'));
hljs.registerLanguage('cpp', require('./languages/cpp.js'));
hljs.registerLanguage('cs', require('./languages/cs.js'));
hljs.registerLanguage('css', require('./languages/css.js'));
hljs.registerLanguage('diff', require('./languages/diff.js'));
hljs.registerLanguage('http', require('./languages/http.js'));
hljs.registerLanguage('ini', require('./languages/ini.js'));
hljs.registerLanguage('java', require('./languages/java.js'));
hljs.registerLanguage('javascript', require('./languages/javascript.js'));
hljs.registerLanguage('json', require('./languages/json.js'));
hljs.registerLanguage('makefile', require('./languages/makefile.js'));
hljs.registerLanguage('xml', require('./languages/xml.js'));
hljs.registerLanguage('markdown', require('./languages/markdown.js'));
hljs.registerLanguage('nginx', require('./languages/nginx.js'));
hljs.registerLanguage('objectivec', require('./languages/objectivec.js'));
hljs.registerLanguage('perl', require('./languages/perl.js'));
hljs.registerLanguage('php', require('./languages/php.js'));
hljs.registerLanguage('python', require('./languages/python.js'));
hljs.registerLanguage('ruby', require('./languages/ruby.js'));
hljs.registerLanguage('sql', require('./languages/sql.js'));
module.exports = hljs;